# Generated by Django 5.0.6 on 2024-05-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjuzik_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='data_ended',
            new_name='date_ended',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='data_started',
            new_name='date_started',
        ),
    ]
